### PR TITLE
Normalize path when using kv v1

### LINKED ISSUE #358: Missing path normalization leads to 301 Moved Permanently from vault for v1 secrets
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.541.1
OS: Linux - 6.14.0-1018-aws
Java: 17.0.17 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
[…]
hashicorp-vault-plugin:377.vc87a_13718939
[…]
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Linux

### Reproduction steps

`withVault` calls with engineVersion 1 and a `path` that has a leading `/` now fail because vault returns a HTTP 301 Moved Permanently for them.

```
withVault(configuration: [engineVersion: 1], vaultSecrets: [
        [path: "/github/token/foo", secretValues: [
            [envVar: 'GITHUB_TOKEN', vaultKey: 'token']]]]) {
        // […]
    }
```

This did not happen with older versions of the plugin. I assume paths were normalized, so no duplicate leading slashes were sent.

### Expected Results

Secret is fetched successfully.

### Actual Results

```
io.github.jopenlibs.vault.VaultException: Vault responded with HTTP status code: 301
 Response body: <a href="/v1/github/token/foo">Moved Permanently</a>.
```

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by icep87**
- It wasn't needed in the previous version of the plugin as the BetterCloud Driver that has now been replaced followed the redirects
- Normalize Vault paths before reads to avoid KV v1 301s when users supply leading/double slashes.
- Added test for the path normalization
- fixes #358

### Testing done

- Added normalizePath, read with normalized path test to VaultAccessorTest.java
- mvn -q -Dtest=VaultAccessorTest test

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests that demonstrate the feature works or the issue is fixed

### CODE REVIEW

File: src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java [hunk 1]
```diff
@@ -41,7 +40,6 @@
 
 public class VaultAccessor implements Serializable {
 
-    @Serial
```
Comment (jetersen) [inline src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java:44]: This should not be removed, this is specific to jenkins

File: src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java [hunk 2]
```diff
@@ -316,4 +316,18 @@ public static VaultConfiguration pullAndMergeConfiguration(Run<?, ?> build,
...
+     */
+    static String normalizePath(String path) {
+        if (StringUtils.isBlank(path)) {
+            return path;
+        }
+        // remove any leading slashes
+        String cleaned = path.replaceFirst("^/+", "");
+        // collapse duplicate separators inside the path
+        return cleaned.replaceAll("/{2,}", "/");
+    }
```
Comment (jetersen) [inline src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java:341]:
```suggestion
    static String normalizePath(String path) {
        if (StringUtils.isBlank(path)) {
            return path;
        }

        // remove any leading slashes
        String cleaned = StringUtils.stripStart(path, "/");
        
        // fast-path: nothing to do in the common case
        if (!cleaned.contains("//")) {
            return cleaned;
        }

        // collapse duplicate separators
        return cleaned.replaceAll("/{2,}", "/");
    }
```

File: src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java (hunk 1 above)
Comment (icep87) [reply src/main/java/com/datapipe/jenkins/vault/VaultAccessor.java:44]: Will re-add it.
